"""Homepage "Featured" section, placed straight after the hero, in all four languages: the featured article (kept as it is in each page)
plus the three Lady Khadijah series (Biography, Poems, Ziyarat explanation) as cards with each language's own titles and links.

  python3 tools/wix_import/build_home_featured.py        (idempotent; run build_home_topics.py after it only if topics changed)
"""
import os, re, sys, html
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from gen_kawthar import PFX, LANGS, ROOT, S
import build_khadijah as K

SERIES = ['lady-khadijah-biography', 'lady-khadijah-poems', 'lady-khadijah-ziyarat']
HEAD = {'en': 'More on Lady Khadijah (p)', 'ar': 'المزيد عن السيدة خديجة (ع)', 'fa': 'بیشتر درباره‌ی حضرت خدیجه (س)', 'ur': 'حضرت خدیجہ (س) کے بارے میں مزید'}
MARK = '<!-- FEATURED — generated by tools/wix_import/build_home_featured.py -->'


def cards(lang):
    out = []
    for ser in SERIES:
        href = f"{PFX[lang]}/articles/{ser}/"
        img = f"/images/home/feat-khadijah-{ser.split('-')[-1]}.jpg"   # three different crops of the Lady Khadijah illustration
        out.append(f'''      <a class="feat-series-card" href="{href}">
        <img src="{img}" alt="" width="480" height="270" loading="lazy" decoding="async">
        <span class="feat-series-body">
          <span class="feat-series-chip">{html.escape(S[lang]['chip'])}</span>
          <span class="feat-series-name">{html.escape(K.NAMES[ser][lang])}</span>
          <span class="feat-series-desc">{html.escape(K.SERIES_DESC[ser][lang])}</span>
        </span>
      </a>''')
    return '\n'.join(out)


def build(lang):
    f = ROOT + ('index.html' if lang == 'en' else f'{lang}/index.html')
    s = open(f, encoding='utf-8').read()
    m = re.search(r'<section class="section featured-section".*?</section>', s, re.S)
    assert m, f
    sec = m.group(0)
    label = re.search(r'<span class="section-label[^>]*>.*?</span>', sec, re.S).group(0)
    title = re.search(r'<h2 class="section-title[^>]*>.*?</h2>', sec, re.S).group(0)
    article = re.search(r'<article class="featured-card">.*?</article>', sec, re.S).group(0)
    new = f'''{MARK}
<section class="section featured-section" aria-labelledby="feat-heading">
  <div class="container">
    {label}
    {title}
    <div class="divider" aria-hidden="true"><span class="divider-gem">◆</span></div>

    {article}

    <h3 class="feat-series-heading">{html.escape(HEAD[lang])}</h3>
    <div class="feat-series">
{cards(lang)}
    </div>
  </div>
</section>

'''
    # remove the old block (with any banner comment in front of it) wherever it is
    start = m.start()
    pre = s[:start]
    cm = re.search(r'(?:<!-- ═+\s*\n\s*FEATURED[^\n]*\n═+ -->\s*|<!-- FEATURED[^>]*-->\s*)+$', pre)
    if cm: start = cm.start()
    end = m.end()
    s = s[:start] + s[end:].lstrip('\n')
    # insert straight after the hero
    h = re.search(r'<section class="hero".*?</section>\n', s, re.S)
    s = s[:h.end()] + '\n' + new + s[h.end():]
    open(f, 'w', encoding='utf-8').write(s)


if __name__ == '__main__':
    for l in LANGS: build(l)
    print('featured section rebuilt in', LANGS)
